# Generated by Django 5.0.2 on 2024-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
