# Generated by Django 5.0.2 on 2024-02-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_post_options_post_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
    ]
