# Generated by Django 5.0.2 on 2024-02-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(auto_created=True, default=True, null=True),
        ),
    ]
