# Generated by Django 5.0.2 on 2024-02-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='followed_by',
        ),
    ]
