# Generated by Django 5.0.2 on 2024-02-29 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_follower_id_follow_followed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowUser',
        ),
    ]
