# Generated by Django 5.0.2 on 2024-03-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_reactcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReactComment',
        ),
    ]
