# Generated by Django 5.0.2 on 2024-03-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_reactcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactcomment',
            name='reaction',
            field=models.CharField(choices=[('H', 'HAHA'), ('S', 'SAD'), ('C', 'CARE'), ('L', 'LOVE')], max_length=1),
        ),
    ]
