# Generated by Django 5.0.2 on 2024-02-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_comments', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
